/**
 * The words of a preset's documentation that belong to no preset in particular: headings, how
 * discovery and masking work, and how each framework's configuration reads in prose. Every locale
 * has the same keys; a preset brings its own text in presets/<id>/doc/<locale>.json.
 *
 * Describers receive the algorithm's configuration and `h`, the renderer's helpers:
 *   h.code(text)  inline code      h.ref(reference)  an algorithm reference
 *   h.file(ref)   a file name      h.lines(ref)      how many lines that file has
 *   h.num(n)      a number         h.unit(unit)      a time unit
 * and return HTML.
 */

const actionEn = (a, h) => (
  a.type === 'PRESERVE' ? 'keep'
    : a.type === 'TRUNCATE' ? 'remove'
      : a.type === 'REDACT' ? (a.redactString !== undefined ? `replace with ${h.code(a.redactString)}` : `each character → ${h.code(a.redactCharacter)}`)
        : h.ref(a.algorithm))
const actionPt = (a, h) => (
  a.type === 'PRESERVE' ? 'mantém'
    : a.type === 'TRUNCATE' ? 'remove'
      : a.type === 'REDACT' ? (a.redactString !== undefined ? `troca por ${h.code(a.redactString)}` : `cada caractere → ${h.code(a.redactCharacter)}`)
        : h.ref(a.algorithm))
const actionEs = (a, h) => (
  a.type === 'PRESERVE' ? 'conserva'
    : a.type === 'TRUNCATE' ? 'elimina'
      : a.type === 'REDACT' ? (a.redactString !== undefined ? `reemplaza por ${h.code(a.redactString)}` : `cada carácter → ${h.code(a.redactCharacter)}`)
        : h.ref(a.algorithm))

export const TEXT = {
  en: {
    eyebrow: 'Delphix Masking · Pre-configured profile set',
    facts: { domains: 'Domains', classifiers: 'Classifiers', algorithms: 'Algorithms' },
    version: 'Version',
    threshold: 'Assignment threshold',
    contents: 'Contents',
    contentsLede: 'The first sections explain what the set is for and how it works. The domain chapters then describe every domain: what it is, how its data is found and how it is masked, with examples. The appendices list every algorithm, file and classifier the set contains.',
    part: 'Part',
    appendix: 'Appendix',
    discoveryTitle: 'How sensitive data is discovered',
    discovery: (threshold) => [
      'A profiling job looks at every column and asks each classifier of the profile set how confident it is that the column belongs to its domain. Classifiers come in four kinds:',
      { list: [
        '**Column name** — regular expressions on the column name. Each rule has a strength: the confidence it gives when it matches.',
        '**Data type** — accepts the column type and length, or rules the domain out. It never assigns a domain on its own.',
        '**Value format** — tests a sample of the values against patterns, some with a check digit. The confidence follows the share of values that match.',
        '**Known values** — looks the sampled values up in lists; for names, word by word.',
      ] },
      `Evidence from the name and from the values is combined per domain, and the column is assigned to the domain with the highest confidence when it reaches the threshold of the profile set — **${threshold}%** here. Values that do not match a format or a list count against their domain by the classifier's reject strength.`,
      'Column-name rules are shown as their alternatives. They ignore case and must not be glued to other letters: `rut` finds `RUT_CLIENTE` and `CLIENTE_RUT` but not `RUTA`. In them, `_?` is an optional underscore, `(a|b)` either form, `s?` an optional letter and `[a-z_]*` any continuation.',
      { tip: 'Profiling proposes; it does not decide. Review the assigned domains before running a masking job, and look for columns the set left unassigned.' },
    ],
    maskingTitle: 'How data is masked',
    masking: [
      'Each domain names one algorithm, applied by the masking job to every column assigned to the domain. Algorithms can be composed: a **Regex Decompose** splits a value into parts and gives each part its own action; a **String Algorithm Chain** applies algorithms one after another. The tree under each domain shows everything its algorithm uses; Appendix A has every configuration in full.',
      'The algorithms are deterministic for the engine key: the same value masks the same way in every table, database and job, so joins between masked systems keep working.',
      { tip: 'The examples in this document were produced by running the algorithms with this tool’s key. On an engine with another key the masked values differ; their shape does not.' },
    ],
    overviewTitle: 'Domains at a glance',
    overviewLede: 'Every domain of the set, how it is found and the algorithm that masks it.',
    overviewHead: ['Domain', 'Found by', 'Algorithm'],
    what: 'What it is',
    found: 'How it is found',
    masked: 'How it is masked',
    examples: 'Examples',
    input: 'Value',
    output: 'Masked',
    kinds: { PATH: 'Column name', TYPE: 'Data type', REGEX: 'Value format', LIST: 'Known values' },
    except: 'except when followed by',
    exclusionList: (id) => `list ${id}`,
    typeAccepts: (types) => `Accepts ${types}; any other type rules the domain out.`,
    typeNames: { String: 'text', Number: 'number', Date: 'date', Binary: 'binary' },
    sqlTypes: { 91: 'DATE', 92: 'TIME', 93: 'TIMESTAMP', 2014: 'TIMESTAMP WITH TIME ZONE' },
    lengthMin: (n) => `length ${n} or more`,
    lengthMax: (n) => `length up to ${n}`,
    lengthRange: (a, b) => `length ${a} to ${b}`,
    or: 'or',
    regexHead: ['Pattern', 'Strength', 'Notes'],
    checksum: (type) => `${type} check digit`,
    partial: 'anywhere in the value',
    cleaned: (regex) => `after removing ${regex}`,
    reject: (p) => `A value that matches none counts ${p} against the domain.`,
    noReject: 'A value that matches none does not count against the domain.',
    listHead: ['List', 'Values', 'Strength', 'First values'],
    tokenized: 'Values are split into words, and each word is looked up.',
    appendixAlgorithms: 'Algorithms',
    appendixAlgorithmsLede: 'Every algorithm of the set in alphabetical order, with its configuration. The one a domain names is the top of its tree; the others are building blocks.',
    usedBy: 'Used by',
    none: 'nothing',
    patterns: 'Patterns, tried in order',
    otherwise: 'otherwise',
    parameters: 'Configuration',
    appendixFiles: 'Files',
    appendixFilesLede: 'Lookup and detection files travel with the set: loading it copies them into the files folder, and sending it to Delphix uploads them.',
    filesHead: ['File', 'Lines', 'Used by', 'First lines'],
    appendixExclusions: 'Exclusion lists',
    appendixExclusionsLede: 'Words that keep a column-name rule from matching when they follow it — so that `NOMBRE_PRODUCTO` is not taken for a person’s name.',
    appendixClassifiers: 'Profile set and classifiers',
    appendixClassifiersLede: (name, threshold, n) => `The profile set ${name} runs these ${n} classifiers, with an assignment threshold of ${threshold}%.`,
    classifiersHead: ['Classifier', 'Kind', 'Domain'],
    yes: 'yes',
    no: 'no',
    units: { SECONDS: 'seconds', MINUTES: 'minutes', HOURS: 'hours', DAYS: 'days', MONTHS: 'months', YEARS: 'years' },
    action: actionEn,
    closedSteps: (n) => `It is made of ${n} algorithms that repeat the same step position by position; each one is in Appendix A.`,
    describe: {
      SecureLookup: (c, h) => `Replaces the value with one of the ${h.num(h.lines(c.lookupFile))} values in ${h.file(c.lookupFile)}, chosen by a keyed hash.`,
      NullSecureLookup: () => 'Secure Lookup that keeps empty values empty.',
      DataCleansing: (c, h) => `Replaces each value found in ${h.file(c.lookupFile)} (${h.num(h.lines(c.lookupFile))} pairs) by its counterpart; values not in the file stay as they are.`,
      RegexDecompose: (c, h) => `${c.maskPatterns.length === 1 ? 'Matches one pattern' : `Tries ${c.maskPatterns.length} patterns in order`} and gives each part of the value its own action; when none matches: ${actionEn(c.fallbackAction ?? { type: 'PRESERVE' }, h)}.`,
      Checkdigit: (c, h) => `Masks the digits with ${h.ref(c.numericAlgorithm)} and recomputes a modulus ${c.modulusNumber} check digit with weights ${h.code(c.weightList.join(' '))}${c.calculateChecksumRightToLeft ? ' from the right' : ''}.`,
      CharacterMapping: (c) => `Maps each character to another of its group (${c.characterGroups.length} groups), keeping length and format.`,
      NumericMapping: (c, h) => `Maps the number to another between ${h.num(c.minValue)} and ${h.num(c.maxValue)}.`,
      PaymentCard: () => 'Replaces the card number with another that passes the Luhn check.',
      Name: (c, h) => `Replaces the name with one of the ${h.num(h.lines(c.lookupFile))} names in ${h.file(c.lookupFile)}.`,
      FullName: (c, h) => `Masks given names with ${h.ref(c.firstNameAlgorithmRef)} and surnames with ${h.ref(c.lastNameAlgorithmRef)}.`,
      StringAlgorithmChain: (c, h) => `Applies ${c.algorithmReferences.map(h.ref).join(' → ')}, in this order.`,
      DateShift: (c, h) => `Moves the date by ${h.num(c.minRange)} to ${h.num(c.maxRange)} ${h.unit(c.unit)}.`,
      DateReplacement: (c, h) => `Replaces the date with one between ${h.code(c.minDate)} and ${h.code(c.maxDate)}.`,
      MinMaxBigDecimal: (c, h) => `Keeps the number between ${h.num(c.minValue)} and ${h.num(c.maxValue)}.`,
      MinMaxLocalDateTime: (c, h) => `Keeps the date between ${h.code(c.minDate)} and ${h.code(c.maxDate)}.`,
      FreeTextRedaction: (c, h) => `Replaces the text matching ${c.regularExpressions?.length ?? 0} patterns with ${h.code(c.regExRedactValue ?? '')}${c.lookupFile ? `, and the ${h.num(h.lines(c.lookupFile))} terms of ${h.file(c.lookupFile)} with ${h.code(c.lookupFileRedactValue ?? '')}` : ''}.`,
      Email: () => 'Masks the e-mail address.',
      Phone: () => 'Generates another phone number in the same format.',
      Tokenization: () => 'Replaces the value with a reversible token.',
      Redact: () => 'Replaces the parts that match regular expressions.',
      SegmentMapping: () => 'Masks the value segment by segment.',
      default: (display) => `${display}.`,
    },
  },

  'pt-BR': {
    eyebrow: 'Delphix Masking · Profile set pré-configurado',
    facts: { domains: 'Domínios', classifiers: 'Classifiers', algorithms: 'Algoritmos' },
    version: 'Versão',
    threshold: 'Limiar de atribuição',
    contents: 'Sumário',
    contentsLede: 'As primeiras seções explicam para que o set serve e como ele funciona. Os capítulos de domínios descrevem cada domínio: o que é, como o dado é encontrado e como é mascarado, com exemplos. Os apêndices listam todos os algoritmos, arquivos e classifiers que o set contém.',
    part: 'Parte',
    appendix: 'Apêndice',
    discoveryTitle: 'Como os dados sensíveis são descobertos',
    discovery: (threshold) => [
      'Um job de profiling olha cada coluna e pergunta a cada classifier do profile set quão confiante ele está de que a coluna pertence ao seu domínio. Há quatro tipos de classifier:',
      { list: [
        '**Nome da coluna** — expressões regulares sobre o nome da coluna. Cada regra tem uma força: a confiança que ela dá quando casa.',
        '**Tipo de dado** — aceita o tipo e o tamanho da coluna, ou descarta o domínio. Sozinho, nunca atribui um domínio.',
        '**Formato do valor** — testa uma amostra dos valores contra padrões, alguns com dígito verificador. A confiança acompanha a proporção de valores que casam.',
        '**Valores conhecidos** — procura os valores da amostra em listas; para nomes, palavra por palavra.',
      ] },
      `A evidência do nome e a dos valores são combinadas por domínio, e a coluna é atribuída ao domínio de maior confiança quando ela alcança o limiar do profile set — **${threshold}%** aqui. Valores que não casam com um formato ou uma lista contam contra o domínio, na força de rejeição do classifier.`,
      'As regras de nome de coluna aparecem como suas alternativas. Elas ignoram maiúsculas e não podem estar coladas a outras letras: `rut` acha `RUT_CLIENTE` e `CLIENTE_RUT`, mas não `RUTA`. Nelas, `_?` é um sublinhado opcional, `(a|b)` uma forma ou outra, `s?` uma letra opcional e `[a-z_]*` qualquer continuação.',
      { tip: 'O profiling propõe; não decide. Revise os domínios atribuídos antes de rodar um job de mascaramento, e procure colunas que o set deixou sem domínio.' },
    ],
    maskingTitle: 'Como os dados são mascarados',
    masking: [
      'Cada domínio nomeia um algoritmo, que o job de mascaramento aplica a todas as colunas atribuídas ao domínio. Algoritmos podem ser compostos: um **Regex Decompose** divide o valor em partes e dá a cada parte sua própria ação; uma **String Algorithm Chain** aplica algoritmos um depois do outro. A árvore sob cada domínio mostra tudo o que o algoritmo usa; o Apêndice A traz cada configuração completa.',
      'Os algoritmos são determinísticos para a chave do engine: o mesmo valor é mascarado do mesmo jeito em todas as tabelas, bancos e jobs, e os joins entre sistemas mascarados continuam funcionando.',
      { tip: 'Os exemplos deste documento foram produzidos executando os algoritmos com a chave desta ferramenta. Num engine com outra chave os valores mascarados mudam; o formato deles, não.' },
    ],
    overviewTitle: 'Os domínios numa visão',
    overviewLede: 'Todos os domínios do set, como são encontrados e o algoritmo que os mascara.',
    overviewHead: ['Domínio', 'Encontrado por', 'Algoritmo'],
    what: 'O que é',
    found: 'Como é encontrado',
    masked: 'Como é mascarado',
    examples: 'Exemplos',
    input: 'Valor',
    output: 'Mascarado',
    kinds: { PATH: 'Nome da coluna', TYPE: 'Tipo de dado', REGEX: 'Formato do valor', LIST: 'Valores conhecidos' },
    except: 'exceto quando seguido de',
    exclusionList: (id) => `lista ${id}`,
    typeAccepts: (types) => `Aceita ${types}; qualquer outro tipo descarta o domínio.`,
    typeNames: { String: 'texto', Number: 'número', Date: 'data', Binary: 'binário' },
    sqlTypes: { 91: 'DATE', 92: 'TIME', 93: 'TIMESTAMP', 2014: 'TIMESTAMP WITH TIME ZONE' },
    lengthMin: (n) => `tamanho ${n} ou mais`,
    lengthMax: (n) => `tamanho até ${n}`,
    lengthRange: (a, b) => `tamanho de ${a} a ${b}`,
    or: 'ou',
    regexHead: ['Padrão', 'Força', 'Observações'],
    checksum: (type) => `dígito verificador ${type}`,
    partial: 'em qualquer parte do valor',
    cleaned: (regex) => `depois de remover ${regex}`,
    reject: (p) => `Um valor que não casa com nenhum conta ${p} contra o domínio.`,
    noReject: 'Um valor que não casa com nenhum não conta contra o domínio.',
    listHead: ['Lista', 'Valores', 'Força', 'Primeiros valores'],
    tokenized: 'Os valores são divididos em palavras, e cada palavra é procurada.',
    appendixAlgorithms: 'Algoritmos',
    appendixAlgorithmsLede: 'Todos os algoritmos do set em ordem alfabética, com a configuração. O que um domínio nomeia é o topo da sua árvore; os demais são peças de montagem.',
    usedBy: 'Usado por',
    none: 'nada',
    patterns: 'Padrões, tentados em ordem',
    otherwise: 'senão',
    parameters: 'Configuração',
    appendixFiles: 'Arquivos',
    appendixFilesLede: 'Os arquivos de lookup e de detecção viajam com o set: carregá-lo os copia para a pasta de arquivos, e enviá-lo ao Delphix faz o upload.',
    filesHead: ['Arquivo', 'Linhas', 'Usado por', 'Primeiras linhas'],
    appendixExclusions: 'Listas de exclusão',
    appendixExclusionsLede: 'Palavras que, logo depois de uma regra de nome de coluna, impedem que ela case — para que `NOMBRE_PRODUCTO` não seja tomado pelo nome de uma pessoa.',
    appendixClassifiers: 'Profile set e classifiers',
    appendixClassifiersLede: (name, threshold, n) => `O profile set ${name} roda estes ${n} classifiers, com limiar de atribuição de ${threshold}%.`,
    classifiersHead: ['Classifier', 'Tipo', 'Domínio'],
    yes: 'sim',
    no: 'não',
    units: { SECONDS: 'segundos', MINUTES: 'minutos', HOURS: 'horas', DAYS: 'dias', MONTHS: 'meses', YEARS: 'anos' },
    action: actionPt,
    closedSteps: (n) => `É formado por ${n} algoritmos que repetem o mesmo passo posição a posição; cada um está no Apêndice A.`,
    describe: {
      SecureLookup: (c, h) => `Troca o valor por um dos ${h.num(h.lines(c.lookupFile))} valores de ${h.file(c.lookupFile)}, escolhido por um hash com chave.`,
      NullSecureLookup: () => 'Secure Lookup que mantém vazios os valores vazios.',
      DataCleansing: (c, h) => `Troca cada valor encontrado em ${h.file(c.lookupFile)} (${h.num(h.lines(c.lookupFile))} pares) pelo seu correspondente; valores fora do arquivo ficam como estão.`,
      RegexDecompose: (c, h) => `${c.maskPatterns.length === 1 ? 'Casa um padrão' : `Tenta ${c.maskPatterns.length} padrões em ordem`} e dá a cada parte do valor sua própria ação; quando nenhum casa: ${actionPt(c.fallbackAction ?? { type: 'PRESERVE' }, h)}.`,
      Checkdigit: (c, h) => `Mascara os dígitos com ${h.ref(c.numericAlgorithm)} e recalcula um dígito verificador módulo ${c.modulusNumber} com pesos ${h.code(c.weightList.join(' '))}${c.calculateChecksumRightToLeft ? ' a partir da direita' : ''}.`,
      CharacterMapping: (c) => `Troca cada caractere por outro do seu grupo (${c.characterGroups.length} grupos), mantendo tamanho e formato.`,
      NumericMapping: (c, h) => `Troca o número por outro entre ${h.num(c.minValue)} e ${h.num(c.maxValue)}.`,
      PaymentCard: () => 'Troca o número do cartão por outro que passa na verificação de Luhn.',
      Name: (c, h) => `Troca o nome por um dos ${h.num(h.lines(c.lookupFile))} nomes de ${h.file(c.lookupFile)}.`,
      FullName: (c, h) => `Mascara os nomes com ${h.ref(c.firstNameAlgorithmRef)} e os sobrenomes com ${h.ref(c.lastNameAlgorithmRef)}.`,
      StringAlgorithmChain: (c, h) => `Aplica ${c.algorithmReferences.map(h.ref).join(' → ')}, nesta ordem.`,
      DateShift: (c, h) => `Desloca a data entre ${h.num(c.minRange)} e ${h.num(c.maxRange)} ${h.unit(c.unit)}.`,
      DateReplacement: (c, h) => `Troca a data por uma entre ${h.code(c.minDate)} e ${h.code(c.maxDate)}.`,
      MinMaxBigDecimal: (c, h) => `Mantém o número entre ${h.num(c.minValue)} e ${h.num(c.maxValue)}.`,
      MinMaxLocalDateTime: (c, h) => `Mantém a data entre ${h.code(c.minDate)} e ${h.code(c.maxDate)}.`,
      FreeTextRedaction: (c, h) => `Troca o texto que casa com ${c.regularExpressions?.length ?? 0} padrões por ${h.code(c.regExRedactValue ?? '')}${c.lookupFile ? `, e os ${h.num(h.lines(c.lookupFile))} termos de ${h.file(c.lookupFile)} por ${h.code(c.lookupFileRedactValue ?? '')}` : ''}.`,
      Email: () => 'Mascara o endereço de e-mail.',
      Phone: () => 'Gera outro número de telefone no mesmo formato.',
      Tokenization: () => 'Troca o valor por um token reversível.',
      Redact: () => 'Troca as partes que casam com expressões regulares.',
      SegmentMapping: () => 'Mascara o valor segmento a segmento.',
      default: (display) => `${display}.`,
    },
  },

  es: {
    eyebrow: 'Delphix Masking · Profile set preconfigurado',
    facts: { domains: 'Dominios', classifiers: 'Classifiers', algorithms: 'Algoritmos' },
    version: 'Versión',
    threshold: 'Umbral de asignación',
    contents: 'Contenido',
    contentsLede: 'Las primeras secciones explican para qué sirve el set y cómo funciona. Los capítulos de dominios describen cada dominio: qué es, cómo se encuentra el dato y cómo se enmascara, con ejemplos. Los apéndices listan todos los algoritmos, archivos y classifiers que contiene el set.',
    part: 'Parte',
    appendix: 'Apéndice',
    discoveryTitle: 'Cómo se descubren los datos sensibles',
    discovery: (threshold) => [
      'Un job de profiling mira cada columna y pregunta a cada classifier del profile set qué tan seguro está de que la columna pertenece a su dominio. Hay cuatro tipos de classifier:',
      { list: [
        '**Nombre de la columna** — expresiones regulares sobre el nombre de la columna. Cada regla tiene una fuerza: la confianza que da cuando coincide.',
        '**Tipo de dato** — acepta el tipo y el largo de la columna, o descarta el dominio. Por sí solo nunca asigna un dominio.',
        '**Formato del valor** — prueba una muestra de los valores contra patrones, algunos con dígito verificador. La confianza sigue la proporción de valores que coinciden.',
        '**Valores conocidos** — busca los valores de la muestra en listas; para nombres, palabra por palabra.',
      ] },
      `La evidencia del nombre y la de los valores se combinan por dominio, y la columna se asigna al dominio de mayor confianza cuando esta alcanza el umbral del profile set — **${threshold}%** aquí. Los valores que no coinciden con un formato o una lista cuentan en contra de su dominio, según la fuerza de rechazo del classifier.`,
      'Las reglas de nombre de columna se muestran como sus alternativas. Ignoran mayúsculas y no pueden ir pegadas a otras letras: `rut` encuentra `RUT_CLIENTE` y `CLIENTE_RUT`, pero no `RUTA`. En ellas, `_?` es un guion bajo opcional, `(a|b)` una forma u otra, `s?` una letra opcional y `[a-z_]*` cualquier continuación.',
      { tip: 'El profiling propone; no decide. Revise los dominios asignados antes de ejecutar un job de enmascaramiento, y busque las columnas que el set dejó sin dominio.' },
    ],
    maskingTitle: 'Cómo se enmascaran los datos',
    masking: [
      'Cada dominio nombra un algoritmo, que el job de enmascaramiento aplica a todas las columnas asignadas al dominio. Los algoritmos se pueden componer: un **Regex Decompose** divide el valor en partes y da a cada parte su propia acción; una **String Algorithm Chain** aplica algoritmos uno tras otro. El árbol bajo cada dominio muestra todo lo que usa su algoritmo; el Apéndice A trae cada configuración completa.',
      'Los algoritmos son deterministas para la clave del engine: el mismo valor se enmascara igual en todas las tablas, bases y jobs, y los joins entre sistemas enmascarados siguen funcionando.',
      { tip: 'Los ejemplos de este documento se produjeron ejecutando los algoritmos con la clave de esta herramienta. En un engine con otra clave los valores enmascarados cambian; su forma, no.' },
    ],
    overviewTitle: 'Los dominios de un vistazo',
    overviewLede: 'Todos los dominios del set, cómo se encuentran y el algoritmo que los enmascara.',
    overviewHead: ['Dominio', 'Encontrado por', 'Algoritmo'],
    what: 'Qué es',
    found: 'Cómo se encuentra',
    masked: 'Cómo se enmascara',
    examples: 'Ejemplos',
    input: 'Valor',
    output: 'Enmascarado',
    kinds: { PATH: 'Nombre de columna', TYPE: 'Tipo de dato', REGEX: 'Formato del valor', LIST: 'Valores conocidos' },
    except: 'salvo cuando le sigue',
    exclusionList: (id) => `lista ${id}`,
    typeAccepts: (types) => `Acepta ${types}; cualquier otro tipo descarta el dominio.`,
    typeNames: { String: 'texto', Number: 'número', Date: 'fecha', Binary: 'binario' },
    sqlTypes: { 91: 'DATE', 92: 'TIME', 93: 'TIMESTAMP', 2014: 'TIMESTAMP WITH TIME ZONE' },
    lengthMin: (n) => `largo ${n} o más`,
    lengthMax: (n) => `largo hasta ${n}`,
    lengthRange: (a, b) => `largo de ${a} a ${b}`,
    or: 'o',
    regexHead: ['Patrón', 'Fuerza', 'Notas'],
    checksum: (type) => `dígito verificador ${type}`,
    partial: 'en cualquier parte del valor',
    cleaned: (regex) => `después de quitar ${regex}`,
    reject: (p) => `Un valor que no coincide con ninguno cuenta ${p} en contra del dominio.`,
    noReject: 'Un valor que no coincide con ninguno no cuenta en contra del dominio.',
    listHead: ['Lista', 'Valores', 'Fuerza', 'Primeros valores'],
    tokenized: 'Los valores se dividen en palabras, y se busca cada palabra.',
    appendixAlgorithms: 'Algoritmos',
    appendixAlgorithmsLede: 'Todos los algoritmos del set en orden alfabético, con su configuración. El que nombra un dominio es la cima de su árbol; los demás son piezas de construcción.',
    usedBy: 'Usado por',
    none: 'nada',
    patterns: 'Patrones, probados en orden',
    otherwise: 'si no',
    parameters: 'Configuración',
    appendixFiles: 'Archivos',
    appendixFilesLede: 'Los archivos de lookup y de detección viajan con el set: cargarlo los copia a la carpeta de archivos, y enviarlo a Delphix los sube.',
    filesHead: ['Archivo', 'Líneas', 'Usado por', 'Primeras líneas'],
    appendixExclusions: 'Listas de exclusión',
    appendixExclusionsLede: 'Palabras que, justo después de una regla de nombre de columna, impiden que coincida — para que `NOMBRE_PRODUCTO` no se tome por el nombre de una persona.',
    appendixClassifiers: 'Profile set y classifiers',
    appendixClassifiersLede: (name, threshold, n) => `El profile set ${name} ejecuta estos ${n} classifiers, con un umbral de asignación de ${threshold}%.`,
    classifiersHead: ['Classifier', 'Tipo', 'Dominio'],
    yes: 'sí',
    no: 'no',
    units: { SECONDS: 'segundos', MINUTES: 'minutos', HOURS: 'horas', DAYS: 'días', MONTHS: 'meses', YEARS: 'años' },
    action: actionEs,
    closedSteps: (n) => `Está formado por ${n} algoritmos que repiten el mismo paso posición por posición; cada uno está en el Apéndice A.`,
    describe: {
      SecureLookup: (c, h) => `Reemplaza el valor por uno de los ${h.num(h.lines(c.lookupFile))} valores de ${h.file(c.lookupFile)}, elegido por un hash con clave.`,
      NullSecureLookup: () => 'Secure Lookup que deja vacíos los valores vacíos.',
      DataCleansing: (c, h) => `Reemplaza cada valor encontrado en ${h.file(c.lookupFile)} (${h.num(h.lines(c.lookupFile))} pares) por su correspondiente; los valores que no están en el archivo quedan igual.`,
      RegexDecompose: (c, h) => `${c.maskPatterns.length === 1 ? 'Busca un patrón' : `Prueba ${c.maskPatterns.length} patrones en orden`} y da a cada parte del valor su propia acción; cuando ninguno coincide: ${actionEs(c.fallbackAction ?? { type: 'PRESERVE' }, h)}.`,
      Checkdigit: (c, h) => `Enmascara los dígitos con ${h.ref(c.numericAlgorithm)} y recalcula un dígito verificador módulo ${c.modulusNumber} con pesos ${h.code(c.weightList.join(' '))}${c.calculateChecksumRightToLeft ? ' desde la derecha' : ''}.`,
      CharacterMapping: (c) => `Reemplaza cada carácter por otro de su grupo (${c.characterGroups.length} grupos), conservando largo y formato.`,
      NumericMapping: (c, h) => `Reemplaza el número por otro entre ${h.num(c.minValue)} y ${h.num(c.maxValue)}.`,
      PaymentCard: () => 'Reemplaza el número de tarjeta por otro que pasa la verificación de Luhn.',
      Name: (c, h) => `Reemplaza el nombre por uno de los ${h.num(h.lines(c.lookupFile))} nombres de ${h.file(c.lookupFile)}.`,
      FullName: (c, h) => `Enmascara los nombres con ${h.ref(c.firstNameAlgorithmRef)} y los apellidos con ${h.ref(c.lastNameAlgorithmRef)}.`,
      StringAlgorithmChain: (c, h) => `Aplica ${c.algorithmReferences.map(h.ref).join(' → ')}, en este orden.`,
      DateShift: (c, h) => `Desplaza la fecha entre ${h.num(c.minRange)} y ${h.num(c.maxRange)} ${h.unit(c.unit)}.`,
      DateReplacement: (c, h) => `Reemplaza la fecha por una entre ${h.code(c.minDate)} y ${h.code(c.maxDate)}.`,
      MinMaxBigDecimal: (c, h) => `Mantiene el número entre ${h.num(c.minValue)} y ${h.num(c.maxValue)}.`,
      MinMaxLocalDateTime: (c, h) => `Mantiene la fecha entre ${h.code(c.minDate)} y ${h.code(c.maxDate)}.`,
      FreeTextRedaction: (c, h) => `Reemplaza el texto que coincide con ${c.regularExpressions?.length ?? 0} patrones por ${h.code(c.regExRedactValue ?? '')}${c.lookupFile ? `, y los ${h.num(h.lines(c.lookupFile))} términos de ${h.file(c.lookupFile)} por ${h.code(c.lookupFileRedactValue ?? '')}` : ''}.`,
      Email: () => 'Enmascara la dirección de correo.',
      Phone: () => 'Genera otro número de teléfono con el mismo formato.',
      Tokenization: () => 'Reemplaza el valor por un token reversible.',
      Redact: () => 'Reemplaza las partes que coinciden con expresiones regulares.',
      SegmentMapping: () => 'Enmascara el valor segmento por segmento.',
      default: (display) => `${display}.`,
    },
  },
}
