import type { AlgoText } from './algo-metadata'

/** Textos en español de cada algoritmo. Las claves coinciden con METADATA en
 *  algo-metadata.ts; las claves de params/labels deben coincidir exactamente con
 *  las entradas pt-BR, porque son rutas con puntos dentro del JSON Schema. */
export const ALGO_TEXT_ES: Record<string, AlgoText> = {
  CharacterMapping: {
    example: { input: 'Juan Pérez123', key: 'clave-secreta' },
    description: 'Asigna a cada carácter de la entrada un sustituto dentro de los grupos de caracteres configurados. Determinista: la misma entrada+clave siempre produce la misma salida. Ideal para enmascarar texto alfanumérico conservando su longitud.',
    inputFormat: 'Cadena de texto de cualquier longitud. Los caracteres fuera de los grupos configurados se conservan sin cambios. P. ej. "Juan Pérez", "ABC123".',
    params: {
      characterGroups: 'Lista de cadenas, cada una define un grupo de caracteres intercambiables (p. ej. "abcdefghijklmnopqrstuvwxyz"). Los caracteres solo se asignan dentro del mismo grupo.',
      caseSensitive: 'Si es verdadero, trata mayúsculas y minúsculas como grupos separados.',
      minMaskedPositions: 'Número mínimo de posiciones que deben enmascararse.',
      preserveRanges: 'Array de {start, length, direction} para conservar partes de la cadena sin enmascarar.',
      preserveLeadingZeros: 'Si es verdadero, conserva los ceros a la izquierda.',
    },
    labels: {
      characterGroups: 'Grupos de caracteres',
      caseSensitive: 'Distingue mayúsculas y minúsculas',
      minMaskedPositions: 'Mínimo de posiciones enmascaradas',
      preserveRanges: 'Intervalos a conservar',
      preserveLeadingZeros: 'Conservar ceros a la izquierda',
    },
  },
  NumericMapping: {
    example: { key: 'clave-num' },
    description: 'Asigna un valor numérico a otro de forma determinista, dentro del intervalo [minValue, maxValue].',
    inputFormat: 'Número entero positivo, sin decimales ni puntuación. P. ej. "12345".',
    params: { minValue: 'Límite inferior del intervalo de salida.', maxValue: 'Límite superior del intervalo de salida.' },
    labels: { minValue: 'Valor mínimo', maxValue: 'Valor máximo' },
  },
  PaymentCard: {
    example: { key: 'clave-tarjeta' },
    description: 'Enmascara un número de tarjeta de pago. Conserva el BIN y/o los últimos dígitos, manteniendo válido el dígito de control Luhn.',
    inputFormat: 'Número de tarjeta, con o sin espacios/guiones. P. ej. "4111 1111 1111 1111"',
    params: { minMaskedPositions: 'Número mínimo de posiciones enmascaradas.', preserve: 'Cuántos dígitos del final de la tarjeta conservar.' },
    labels: { minMaskedPositions: 'Mínimo de posiciones enmascaradas', preserve: 'Dígitos finales a conservar' },
  },
  CharacterReplacement: {
    example: { input: 'Un texto de ejemplo', key: 'clave' },
    description: 'Aplica reglas de sustitución carácter a carácter: cada regla define qué caracteres de la entrada se cambian y por cuál. Útil para normalizar o redactar caracteres concretos (p. ej. sustituir las vocales por "*").',
    inputFormat: 'Cadena de texto de cualquier longitud. P. ej. "Un texto 123".',
    params: {
      stringAlgorithm: 'Algoritmo de enmascaramiento aplicado a la entrada antes de las reglas de sustitución. Indica el nombre de una instancia del catálogo. Su resultado pasa después por replacementRules.',
      replacementRules: 'Lista de reglas de sustitución aplicadas en secuencia. Cada regla define un conjunto de caracteres a detectar y el carácter que los sustituye.',
      'replacementRules.filteredCharacters': 'Caracteres que esta regla detecta en la entrada (versión simple: cuando no usas conjuntos separados de entrada/salida). Cada aparición de cualquier carácter de esta lista se sustituye por replacementCharacter.',
      'replacementRules.replacementCharacter': 'Carácter único que sustituye a cada carácter encontrado en filteredCharacters. P. ej. "*" convierte "Juan" en "J*an" (si filteredCharacters = ["u"]).',
      'replacementRules.inputFilteredCharacters': 'Caracteres que esta regla detecta en la entrada (versión avanzada con conjuntos separados de entrada/salida). Alternativa a filteredCharacters — permite usar conjuntos distintos para leer y escribir.',
      'replacementRules.inputReplacementCharacter': 'Carácter usado cuando la coincidencia viene de inputFilteredCharacters. En la salida final lo sustituye outputReplacementCharacter.',
      'replacementRules.outputFilteredCharacters': 'Caracteres que se sustituirán si aparecen en la salida de otro algoritmo (stringAlgorithm). Se usa junto con outputReplacementCharacter.',
      'replacementRules.outputReplacementCharacter': 'Carácter que sustituye a los caracteres encontrados en outputFilteredCharacters.',
      requireInputChange: 'Si es verdadero, exige que se haya hecho al menos una sustitución. Si ninguna regla cambió la entrada, el algoritmo lanza un error. Útil para garantizar que el enmascaramiento realmente alteró el valor.',
      filterAccents: 'Elimina los acentos antes de aplicar las reglas, después, en ambas etapas o nunca. INPUT = elimina los acentos de la entrada antes de procesar las reglas. OUTPUT = elimina los acentos del resultado final. BOTH = elimina en ambas etapas. NONE = no elimina acentos (por defecto).',
    },
    labels: {
      stringAlgorithm: 'Algoritmo previo (aplicado antes de las reglas)',
      replacementRules: 'Reglas de sustitución',
      'replacementRules.filteredCharacters': 'Caracteres a sustituir',
      'replacementRules.replacementCharacter': 'Carácter sustituto',
      'replacementRules.inputFilteredCharacters': 'Caracteres de entrada a detectar (avanzado)',
      'replacementRules.inputReplacementCharacter': 'Sustituto para inputFilteredCharacters',
      'replacementRules.outputFilteredCharacters': 'Caracteres de salida a sustituir (avanzado)',
      'replacementRules.outputReplacementCharacter': 'Sustituto para outputFilteredCharacters',
      requireInputChange: 'Exigir al menos una sustitución',
      filterAccents: 'Eliminación de acentos',
    },
  },
  SegmentMapping: {
    example: { key: 'clave-id' },
    description: 'Divide la cadena en segmentos de longitud fija y enmascara cada uno de forma independiente. Ideal para documentos con formato definido: identificadores fiscales, códigos postales, códigos de barras.',
    inputFormat: 'Cadena con formato fijo. Los separadores (puntos, guiones, barras) se omiten automáticamente si autoIgnoreCharacters=true. P. ej. "123.456.789-09", "12.345.678/0001-90".',
    params: {
      segments: 'Obligatorio. Lista de segmentos en el orden en que aparecen en el valor (ignorando los ignoreCharacters). Cada segmento define su longitud y cómo debe tratarse.',
      'segments.length': 'Obligatorio. Cuántos caracteres abarca este segmento (los caracteres ignorados no cuentan). P. ej. en "123.456.789-09" el primer segmento tiene length=3.',
      'segments.segmentType': 'Obligatorio. MASK_NUMERIC = enmascara los dígitos sustituyéndolos por otros dígitos aleatorios (0-9). MASK_ALPHANUMERIC = enmascara con caracteres alfanuméricos. PRESERVE = mantiene los caracteres originales sin cambios. CONSTANT = sustituye todo el segmento por un valor fijo definido en maskValues.',
      'segments.inputValues': 'Conjunto de caracteres válidos para este segmento en la entrada, como una cadena continua. P. ej. "0123456789" para aceptar solo dígitos. Si la entrada tiene un carácter fuera de este conjunto, el comportamiento depende de la configuración. Déjalo vacío para aceptar cualquier carácter.',
      'segments.maskValues': 'Conjunto de caracteres usados como reserva de sustitución para este segmento, como una cadena continua. P. ej. "123456789" (sin cero) hace que el segmento enmascarado nunca empiece por 0. Déjalo vacío para usar el conjunto por defecto del tipo (0-9 para MASK_NUMERIC).',
      ignoreCharacters: 'Códigos ASCII de los caracteres a omitir al dividir la cadena en segmentos. P. ej. 46 = punto, 45 = guion, 47 = barra. Estos caracteres se saltan al contar las posiciones de los segmentos y se reponen en la salida en su lugar original.',
      autoIgnoreCharacters: 'Si es verdadero, detecta automáticamente los caracteres no alfanuméricos y los omite al dividir en segmentos — equivale a listar a mano todos los separadores en ignoreCharacters. Actívalo para documentos y códigos postales sin tener que buscar los códigos ASCII.',
      allowShortSegments: 'Si es verdadero, acepta entradas más cortas que la longitud total definida por los segmentos. Los segmentos finales incompletos se procesan con lo que haya. false (por defecto) = lanza un error si la entrada es más corta de lo esperado.',
      processPreserveBeforeIgnore: 'Controla el orden entre los caracteres ignorados y los segmentos PRESERVE. true = los segmentos PRESERVE se calculan antes de eliminar los caracteres ignorados (útil cuando un separador cae dentro de un segmento PRESERVE). false (por defecto) = los caracteres ignorados se eliminan antes de calcular las posiciones de los segmentos.',
    },
    labels: {
      segments: 'Segmentos',
      'segments.length': 'Longitud (caracteres)',
      'segments.segmentType': 'Tipo de segmento',
      'segments.inputValues': 'Caracteres válidos en la entrada (conjunto de entrada)',
      'segments.maskValues': 'Caracteres usados en la sustitución (conjunto de salida)',
      ignoreCharacters: 'Caracteres a ignorar (códigos ASCII)',
      autoIgnoreCharacters: 'Detectar separadores automáticamente',
      allowShortSegments: 'Aceptar entradas más cortas de lo esperado',
      processPreserveBeforeIgnore: 'Calcular PRESERVE antes de quitar los ignorados',
    },
  },
  Shuffle: {
    example: { batchRows: ['María García', 'Juan López', 'Pedro Martínez', 'Ana Sánchez', 'Carlos Romero'] },
    description: 'Redistribuye los valores entre los registros al azar — cada fila recibe el valor de otra, conservando el conjunto original. El orden cambia en cada ejecución (no es determinista): es intencionado, porque una permutación reproducible permitiría repetir el barajado y desanonimizar los datos. Funciona en modo lote: necesita varios valores a la vez.',
    inputFormat: 'Varios valores de texto (uno por fila de la tabla). Cada valor debe tener al menos minimumShuffleSize caracteres. Los valores se intercambian entre filas — no se inventa ninguno, solo cambia la posición. Cada clic en "Barajar lote" da un orden distinto.',
    params: { minimumShuffleSize: 'Longitud mínima que debe tener un valor para ser barajado (por defecto: 3).' },
    labels: { minimumShuffleSize: 'Tamaño mínimo' },
  },
  StringAlgorithmChain: {
    example: { input: 'Juan Perez', key: 'clave-chain' },
    description: 'Encadena varios algoritmos en secuencia: la salida de cada uno es la entrada del siguiente. Mínimo 2 algoritmos. Los nombres deben ser instancias del catálogo incorporado (p. ej. "dlpx-core:FirstName") o del Masking Engine.',
    inputFormat: 'Cadena de texto compatible con el primer algoritmo de la cadena. El ejemplo encadena nombres: FirstName → LastName.',
    params: { algorithmReferences: 'Array de referencias a algoritmos por nombre de instancia. Mínimo: 2 entradas. P. ej. [{ name: "dlpx-core:FirstName" }, { name: "dlpx-core:LastName" }].' },
    labels: { algorithmReferences: 'Algoritmos en secuencia' },
  },
  RegexDecompose: {
    example: { input: 'usuario@empresa.com' },
    description: 'Descompone la cadena en partes mediante una expresión regular y aplica una acción distinta a cada parte. La regex debe coincidir con toda la cadena; cada grupo de captura (paréntesis) recibe su propia acción. El texto entre grupos se conserva automáticamente.',
    inputFormat: 'Cualquier cadena. El algoritmo prueba cada patrón en orden hasta que uno coincide. Si ninguno coincide, se aplica la "Acción de reserva". P. ej. "usuario@empresa.com" con la regex "([^@]+)(@.+)" → grupo 1 = "usuario", grupo 2 = "@empresa.com".',
    params: {
      maskPatterns: 'Lista de patrones probados en orden. Se usa el primero cuya regex coincida con toda la cadena. Cada patrón tiene una regex y una lista de acciones — debe haber exactamente una acción por grupo de captura (paréntesis).',
      'maskPatterns.regex': 'Expresión regular que debe coincidir con TODA la cadena (anclada implícitamente). Usa grupos de captura (paréntesis) para delimitar las partes que reciben acciones. El texto entre grupos se conserva automáticamente.',
      'maskPatterns.actions': 'Una acción por grupo de captura, en el mismo orden que los paréntesis de la regex. Si la regex tiene 2 grupos, indica 2 acciones.',
      'maskPatterns.actions.type': 'PRESERVE — mantiene el texto original del grupo sin cambios. TRUNCATE — elimina el grupo por completo (lo sustituye por una cadena vacía). REDACT — sustituye el grupo por un texto o carácter fijo (configúralo abajo). APPLY_ALGORITHM — pasa el grupo por un algoritmo de enmascaramiento (elígelo abajo).',
      'maskPatterns.actions.redactString': 'Texto fijo que sustituye todo el grupo. P. ej. "***" convierte "juan" en "***". Úsalo cuando quieras una sustitución uniforme sin importar la longitud. Solo se usa cuando el tipo es REDACT.',
      'maskPatterns.actions.redactCharacter': 'Carácter único usado para sustituir individualmente cada carácter del grupo. P. ej. "X" convierte "juan" en "XXXX" (conserva la longitud). Solo se usa cuando el tipo es REDACT. Es excluyente con "Texto sustituto fijo" — usa uno u otro.',
      'maskPatterns.actions.algorithm': 'Algoritmo de enmascaramiento aplicado al grupo. Elige una prueba/algoritmo guardado en el desplegable, o escribe directamente un nombre del catálogo incorporado (p. ej. dlpx-core:FirstName). Solo se usa cuando el tipo es APPLY_ALGORITHM.',
      fallbackAction: 'Acción aplicada cuando la cadena no coincide con ningún patrón. Si "Exigir coincidencia" está activo, esta acción se ignora y el algoritmo lanza un error.',
      'fallbackAction.type': 'PRESERVE — devuelve el valor original sin cambios. TRUNCATE — devuelve una cadena vacía. REDACT — sustituye todo el valor. APPLY_ALGORITHM — pasa el valor por un algoritmo.',
      'fallbackAction.redactString': 'Texto fijo que sustituye todo el valor en la reserva.',
      'fallbackAction.redactCharacter': 'Carácter usado para sustituir cada carácter del valor en la reserva.',
      'fallbackAction.algorithm': 'Algoritmo aplicado a todo el valor en la reserva.',
      trimInput: 'Elimina espacios y saltos de línea de los extremos del valor antes de intentar la coincidencia. Útil cuando los datos vienen con relleno de la base de datos.',
      requireMask: 'Si está activo, lanza un error cuando la cadena no coincide con ningún patrón (en vez de usar la reserva). Úsalo cuando los valores fuera del formato esperado deban rechazarse.',
      maxInputLength: 'Longitud máxima permitida del valor de entrada, en caracteres. Los valores más largos dan error. Déjalo vacío para no imponer límite.',
    },
    labels: {
      maskPatterns: 'Patrones de enmascaramiento',
      'maskPatterns.regex': 'Regex (debe coincidir con toda la cadena)',
      'maskPatterns.actions': 'Acciones por grupo de captura',
      'maskPatterns.actions.type': 'Tipo de acción',
      'maskPatterns.actions.redactString': 'Texto sustituto fijo',
      'maskPatterns.actions.redactCharacter': 'Carácter de sustitución (conserva la longitud)',
      'maskPatterns.actions.algorithm': 'Algoritmo a aplicar',
      fallbackAction: 'Acción de reserva (cuando ningún patrón coincide)',
      'fallbackAction.type': 'Tipo de acción',
      'fallbackAction.redactString': 'Texto sustituto fijo',
      'fallbackAction.redactCharacter': 'Carácter de sustitución',
      'fallbackAction.algorithm': 'Algoritmo a aplicar',
      trimInput: 'Quitar espacios de los extremos antes de procesar',
      requireMask: 'Exigir coincidencia (error si ningún patrón coincide)',
      maxInputLength: 'Longitud máxima de la entrada (caracteres)',
    },
  },
  FreeTextRedaction: {
    example: { input: 'Contacta con Juan por correo en juan.perez@empresa.com.' },
    description: 'Encuentra y redacta entidades sensibles en texto libre mediante expresiones regulares y/o un archivo de lookup. El resto se conserva.',
    inputFormat: 'Texto libre. P. ej. "Contacta con Juan en juan@empresa.com o en el 555-0100."',
    params: {
      regularExpressions: 'Array de {patternString} con las regex que identifican los fragmentos a redactar.',
      isDenyList: 'true = lista de bloqueo: redacta las coincidencias. false = lista de permitidos: redacta todo lo que NO coincide.',
      regExRedactValue: 'Texto que sustituye a los fragmentos encontrados por las expresiones regulares.',
      lookupFile: 'Archivo de texto con una lista de términos (uno por línea) a buscar en la entrada. Cada aparición encontrada se redacta.',
      lookupFileRedactValue: 'Texto que sustituye a los fragmentos encontrados mediante el archivo de lookup (independiente de regExRedactValue).',
    },
    labels: {
      regularExpressions: 'Expresiones regulares',
      isDenyList: 'Modo lista de bloqueo',
      regExRedactValue: 'Sustitución para coincidencias de regex',
      lookupFile: 'Archivo de términos (lookup)',
      lookupFileRedactValue: 'Sustitución para coincidencias del archivo',
    },
  },
  Redact: {
    example: { input: 'Contacta con Juan por correo en juan.perez@empresa.com.' },
    description: 'Sustituye los fragmentos del valor que coinciden con expresiones regulares por el texto de sustitución configurado. Si no hay ninguna regex configurada, devuelve el valor de entrada sin enmascarar.',
    inputFormat: 'Cualquier cadena de texto. Los fragmentos que coincidan con las regex configuradas se redactan.',
    params: { regexRedact: 'Mapa de {regex → texto_de_sustitución}. Si está vacío, se redacta todo el valor.' },
    labels: { regexRedact: 'Mapeo regex → sustitución' },
  },
  MinMaxBigDecimal: {
    example: { key: 'clave-decimal' },
    description: 'Limita un número decimal al intervalo [minValue, maxValue]: devuelve el valor sin cambios si ya está dentro, minValue si es menor, o maxValue si es mayor.',
    inputFormat: 'Número decimal. P. ej. "5000.50", "3.14"',
    params: { minValue: 'Obligatorio. Límite inferior.', maxValue: 'Obligatorio. Límite superior.', nonConformingDataDefaultValue: 'Valor devuelto cuando la entrada no es un número válido. Si está vacío, el algoritmo lanza un error de dato no conforme.' },
    labels: { minValue: 'Valor mínimo', maxValue: 'Valor máximo', nonConformingDataDefaultValue: 'Valor por defecto para dato inválido' },
  },
  MinMaxLocalDateTime: {
    example: { key: 'clave-fecha' },
    description: 'Limita una fecha/hora al intervalo [minDate, maxDate]: devuelve el valor sin cambios si ya está dentro, minDate si es anterior, o maxDate si es posterior.',
    inputFormat: 'Fecha/hora en formato ISO. P. ej. "2024-03-15T14:30:00"',
    params: { minDate: 'Obligatorio. Fecha/hora mínima (formato ISO).', maxDate: 'Obligatorio. Fecha/hora máxima (formato ISO).', nonConformingDataDefaultValue: 'Valor devuelto cuando la entrada no es una fecha/hora válida. Si está vacío, el algoritmo lanza un error de dato no conforme.' },
    labels: { minDate: 'Fecha/hora mínima', maxDate: 'Fecha/hora máxima', nonConformingDataDefaultValue: 'Valor por defecto para dato inválido' },
  },
  NumericExpression: {
    description: 'Evalúa una expresión Java de una línea sobre el valor numérico de entrada y devuelve el resultado como BigDecimal. La expresión tiene acceso a la variable "input" (el valor de entrada como BigDecimal) y a "seed" (un long derivado de la clave, útil para enmascaramiento determinista). Se pueden definir constantes con nombre adicionales en el campo "constants".',
    inputFormat: 'Número (entero o decimal). P. ej. "1000", "3.14"',
    params: {
      expression: 'Obligatorio. Expresión Java válida que devuelve un BigDecimal. Variables disponibles: "input" (BigDecimal con el valor de entrada) y "seed" (long determinista derivado de la clave). P. ej. input.multiply(new java.math.BigDecimal(2)) — duplica el valor. P. ej. new java.math.BigDecimal(seed % 9000 + 1000) — genera un valor entre 1000 y 9999 a partir de la clave.',
      inputType: 'Cómo interpretar la entrada antes de pasarla a la expresión: DOUBLE, LONG o BIG_DECIMAL (por defecto).',
      constants: 'Constantes con nombre accesibles desde la expresión. Cada constante tiene un "name" y un "value" (cadena). P. ej. name="tasa", value="0.8" — se usa en la expresión como new java.math.BigDecimal(tasa).',
      nonConformingDataDefaultValue: 'Valor devuelto cuando la entrada no es un número válido. Si está vacío, el algoritmo lanza un error de dato no conforme.',
    },
    labels: { expression: 'Expresión Java', inputType: 'Tipo numérico de entrada', constants: 'Constantes', nonConformingDataDefaultValue: 'Valor por defecto para dato inválido' },
  },
  RepeatFirstDigit: {
    description: 'Enmascara los 4 dígitos finales repitiendo 4 veces el primero de ellos.',
    inputFormat: 'Cadena numérica con exactamente 4, 9, 10 o 14 dígitos (sin puntuación). P. ej. "1234", "123456789".',
  },
  DateShift: {
    example: { key: 'clave-fecha' },
    description: 'Desplaza una fecha/hora una cantidad aleatoria dentro del intervalo [minRange, maxRange]. El desplazamiento es determinista según la clave: la misma entrada+clave siempre produce el mismo resultado.',
    inputFormat: 'Fecha o fecha/hora en ISO 8601: "yyyy-MM-dd" o "yyyy-MM-ddTHH:mm:ss". P. ej. "2024-03-15", "2024-03-15T14:30:00".',
    params: {
      minRange: 'Desplazamiento mínimo, en unidades de "unit". Usa un valor negativo para permitir desplazar hacia el pasado. P. ej. -365 con unit=DAYS permite retroceder hasta un año.',
      maxRange: 'Desplazamiento máximo, en unidades de "unit". Usa un valor positivo para permitir desplazar hacia el futuro. P. ej. 365 con unit=DAYS permite avanzar hasta un año.',
      unit: 'Unidad del desplazamiento: SECONDS, MINUTES, HOURS, DAYS, MONTHS, YEARS.',
      roll: 'Controla qué pasa cuando el desplazamiento cae en una fecha inválida — relevante sobre todo con unit=MONTHS o YEARS. P. ej. 31 de enero + 1 mes = 31 de febrero, que no existe. true (roll) = la fecha "encoge" al último día válido del mes destino (→ 28 feb). false (add) = la fecha desborda al mes siguiente (→ 3 mar). Ante la duda, usa false.',
    },
    labels: {
      minRange: 'Desplazamiento mínimo',
      maxRange: 'Desplazamiento máximo',
      unit: 'Unidad de tiempo',
      roll: 'Roll (ajustar al último día válido) en vez de desbordar',
    },
  },
  DateShiftDiscrete: {
    example: { key: 'clave-fecha' },
    description: 'Variante de Date Shift con un conjunto discreto de desplazamientos posibles, definidos mediante un archivo de configuración.',
    inputFormat: 'Fecha o fecha/hora en ISO 8601: "yyyy-MM-dd" o "yyyy-MM-ddTHH:mm:ss". P. ej. "2024-03-15", "2024-03-15T14:30:00".',
  },
  DateReplacement: {
    example: { key: 'clave-fecha' },
    description: 'Sustituye la fecha/hora por un valor absoluto aleatorio dentro del intervalo [minDate, maxDate]. Las fechas de configuración deben usar el formato "yyyy-MM-ddTHH:mm:ss".',
    inputFormat: 'Fecha/hora en ISO 8601: "yyyy-MM-ddTHH:mm:ss". P. ej. "1985-07-20T00:00:00".',
    params: { minDate: 'Fecha mínima posible (formato: "yyyy-MM-ddTHH:mm:ss").', maxDate: 'Fecha máxima posible (formato: "yyyy-MM-ddTHH:mm:ss").', unit: 'SECONDS, MINUTES, HOURS, DAYS.' },
    labels: { minDate: 'Fecha mínima', maxDate: 'Fecha máxima', unit: 'Unidad de tiempo' },
  },
  SecureLookup: {
    example: { input: 'Juan Pérez', key: 'clave-lookup', sampleFiles: { 'lookupFile': 'firstnames.es.txt' } },
    description: 'Sustituye el valor por un elemento de un archivo de lookup, elegido de forma determinista mediante hash. La misma entrada+clave siempre selecciona el mismo sustituto del archivo.',
    inputFormat: 'Cualquier cadena no nula. El algoritmo calcula un hash del valor+clave y lo usa para seleccionar una línea del archivo de lookup.',
    params: {
      lookupFile: 'Obligatorio. Archivo de texto con un valor sustituto por línea. El algoritmo usa el hash de la entrada para elegir qué línea devolver. Cuantas más líneas, mayor variedad de sustitutos.',
      hashMethod: 'Algoritmo usado para derivar el índice dentro del archivo de lookup. SHA256 = hash criptográfico seguro, determinista según la clave (opción recomendada). LEGACY = método de hash antiguo, mantenido por compatibilidad. RANDOMIZE = selección aleatoria no determinista (cada ejecución puede devolver un valor distinto).',
      maskedValueCase: 'Capitalización aplicada al valor devuelto del archivo. PRESERVE_LOOKUP_FILE = lo devuelve tal cual aparece en el archivo. PRESERVE_INPUT = aplica al sustituto la misma capitalización de la entrada (p. ej. entrada en mayúsculas → sustituto en mayúsculas). ALL_LOWER = fuerza minúsculas. ALL_UPPER = fuerza mayúsculas.',
      inputCaseSensitive: 'Si es verdadero, "Juan" y "JUAN" se tratan como valores distintos y pueden recibir sustitutos distintos. Si es falso, la comparación ignora mayúsculas y minúsculas antes del hash.',
      trimWhitespaceFromInput: 'Si es verdadero, elimina espacios y tabuladores de los extremos de la entrada antes de calcular el hash. Útil cuando los datos vienen con relleno de la base de datos y quieres que "  Juan  " produzca el mismo resultado que "Juan".',
      trimWhitespaceInLookupFile: 'Si es verdadero, elimina espacios y tabuladores de los extremos de cada línea del archivo de lookup al cargarlo. Evita que las líneas con espacios sobrantes se traten como valores distintos.',
    },
    labels: {
      lookupFile: 'Archivo de lookup (un valor por línea)',
      hashMethod: 'Método de selección del sustituto',
      maskedValueCase: 'Capitalización del resultado',
      inputCaseSensitive: 'Distinguir mayúsculas y minúsculas en la entrada',
      trimWhitespaceFromInput: 'Quitar espacios de la entrada antes del hash',
      trimWhitespaceInLookupFile: 'Quitar espacios de las líneas del archivo de lookup',
    },
  },
  NullSecureLookup: {
    example: { input: 'valor-sensible', key: 'clave-lookup' },
    description: 'Variante de Secure Lookup con tratamiento de valores nulos. No tiene parámetros configurables — usa el archivo de lookup incorporado en el plugin. En el runner standalone devuelve null para cualquier entrada (comportamiento esperado sin el contexto del Masking Engine).',
    inputFormat: 'Cualquier cadena. En el runner standalone la salida siempre es null (sin contexto de motor). En el Masking Engine, si la entrada es null devuelve null; en caso contrario aplica el lookup configurado.',
  },
  Mapping: {
    example: { config: { mappingSet: { algorithmName: 'mapping-set-predeterminado' } }, input: 'cliente@email.com' },
    description: 'Mantiene un mapeo persistente uno a uno de originales a sustitutos, garantizando la consistencia referencial: el mismo valor original recibe siempre el mismo sustituto en todas las tablas. Requiere la base de datos de mapeo — no funciona en el runner standalone.',
    inputFormat: 'Cualquier cadena. El algoritmo consulta (o crea) un registro en el mapping set y devuelve siempre el mismo sustituto para cada valor original.',
    params: {
      mappingSet: 'Obligatorio. Referencia al conjunto de mapeo que almacena las correspondencias. En el runner standalone esa base de datos no está disponible y el algoritmo fallará.',
      'mappingSet.algorithmName': 'Obligatorio. Nombre del mapping set en el Masking Engine — identifica qué conjunto de mapeos usar. P. ej. "client-name-mapping".',
      'mappingSet.host': 'Host de la base de datos donde está el mapping set. Se usa cuando el mapping set está en una instancia remota del Masking Engine.',
      'mappingSet.port': 'Puerto de la base de datos remota del mapping set.',
      'mappingSet.database': 'Nombre de la base de datos remota del mapping set.',
      'mappingSet.schema': 'Esquema de la base de datos remota del mapping set.',
      'mappingSet.isRemote': 'Si es verdadero, el mapping set está en una instancia remota del Masking Engine (usando host/port/database/schema de arriba). Si es falso, se usa la instancia local.',
      'mappingSet.mappingLookupKey': 'Clave adicional usada para particionar el mapping set. Permite que un mismo mapping set sirva a varios contextos aislados.',
      'mappingSet.propertiesRef': 'Archivo de propiedades con la configuración de conexión a la base de datos remota del mapping set (alternativa a definir host/port/database/schema por separado).',
      ignoreCharacters: 'Códigos ASCII de los caracteres a eliminar de la entrada antes de buscarla en el mapping set. P. ej. 45 = guion, 46 = punto. Útil para llevar documentos con y sin formato al mismo mapeo.',
    },
    labels: {
      mappingSet: 'Conjunto de mapeo',
      'mappingSet.algorithmName': 'Nombre del mapping set',
      'mappingSet.host': 'Host de la base remota',
      'mappingSet.port': 'Puerto de la base remota',
      'mappingSet.database': 'Base de datos remota',
      'mappingSet.schema': 'Esquema de la base remota',
      'mappingSet.isRemote': 'Mapping set remoto',
      'mappingSet.mappingLookupKey': 'Clave de partición del mapping set',
      'mappingSet.propertiesRef': 'Archivo de propiedades de conexión',
      ignoreCharacters: 'Caracteres a ignorar en la entrada (códigos ASCII)',
    },
  },
  DataCleansing: {
    example: { input: 'MAD', sampleFiles: { 'lookupFile': 'mapping.es.csv' } },
    description: 'Sustituye el valor por la correspondencia definida en un archivo de mapeo (original → sustituto). A diferencia de Secure Lookup, el mapeo es explícito y determinista: tú controlas exactamente qué valor se convierte en cuál.',
    inputFormat: 'Cadena que debería tener correspondencia en el archivo de mapeo. Si no la hay, el comportamiento por defecto es devolver el valor original sin cambios. P. ej. "MAD" → "Madrid", "M" → "Masculino".',
    params: {
      lookupFile: 'Obligatorio. Archivo de texto con un mapeo por línea. Cada línea contiene el valor original y el sustituto, separados por el delimitador. Con delimiter=",": "MAD,Madrid" o "masculino,M".',
      delimiter: 'Separador entre el valor original y el sustituto en cada línea del archivo. P. ej. "," para CSV, ";" para punto y coma, "\\t" para tabulador. Si se omite, se usa el tabulador.',
      caseSensitive: 'Si es verdadero, "MAD" y "mad" se tratan como valores distintos y cada uno necesita su propia entrada en el archivo. Si es falso (recomendado en la mayoría de los casos), la comparación ignora mayúsculas y minúsculas.',
      trimWhitespace: 'Si es verdadero, elimina espacios y tabuladores de los extremos de la entrada y de cada línea del archivo antes de comparar. Evita fallos de correspondencia por espacios sobrantes en la base de datos o en el archivo.',
    },
    labels: {
      lookupFile: 'Archivo de mapeo (original → sustituto)',
      delimiter: 'Delimitador entre original y sustituto',
      caseSensitive: 'Distinguir mayúsculas y minúsculas',
      trimWhitespace: 'Quitar espacios de los extremos antes de comparar',
    },
  },
  Email: {
    example: { input: 'juan.perez@empresa.com', key: 'clave-email' },
    description: 'Enmascara una dirección de correo generando una dirección sintética.',
    inputFormat: 'Dirección de correo válida. P. ej. "juan.perez@empresa.com"',
    params: {
      nameAction: 'Obligatorio. Cómo enmascarar la parte del nombre: UNIQUE, LOOKUP, APPLY_ALGORITHM, APPLY_FIRSTNAME_AND_LASTNAME_ALGORITHMS.',
      domainAction: 'Obligatorio. Cómo enmascarar el dominio: REPLACEMENT (sustituir por domainReplacementString), APPLY_ALGORITHM, PRESERVE.',
      domainReplacementString: 'Dominio sustituto cuando domainAction=REPLACEMENT. P. ej. "example.com".',
      errorHandlingAction: 'Acción en caso de error: EXCEPTION, CHARACTER_MAPPING, PRESERVE.',
    },
    labels: {
      nameAction: 'Acción para el nombre',
      domainAction: 'Acción para el dominio',
      domainReplacementString: 'Dominio sustituto',
      errorHandlingAction: 'Acción en caso de error',
    },
  },
  Phone: {
    example: { input: '+34 612 345 678', key: 'clave-telefono' },
    description: 'Genera un número de teléfono sintético conservando el formato original.',
    inputFormat: 'Número de teléfono en cualquier formato. P. ej. "(11) 99999-8888"',
    params: { isPhoneUnique: 'Obligatorio. Si es verdadero, garantiza sustitutos únicos.' },
    labels: { isPhoneUnique: 'Garantizar números únicos' },
  },
  Name: {
    example: { input: 'Juan', key: 'clave-nombre', sampleFiles: { 'lookupFile': 'firstnames.es.txt' } },
    description: 'Sustituye un nombre simple (nombre de pila o apellido) por otro extraído de forma determinista de un archivo de lookup. La misma entrada+clave siempre produce el mismo sustituto.',
    inputFormat: 'Nombre simple, sin separadores. P. ej. "Juan", "Pérez", "María". Para nombres compuestos usa FullName.',
    params: {
      lookupFile: 'Obligatorio. Archivo de texto con un nombre por línea. El algoritmo extrae un nombre de ese archivo de forma determinista (según la clave). Sirve cualquier lista — nombres de pila, apellidos, etc.',
      maskedValueCase: 'Capitalización aplicada al nombre extraído del archivo. PRESERVE_LOOKUP_FILE = usa el nombre tal cual aparece en el archivo. PRESERVE_INPUT = aplica al sustituto la misma capitalización de la entrada (p. ej. entrada "JUAN" → sustituto en mayúsculas). ALL_LOWER = todo en minúsculas. ALL_UPPER = todo en mayúsculas.',
      particlesToRemoveFile: 'Archivo con las partículas a eliminar de la entrada antes del lookup (una por línea). P. ej. "de", "del", "la" — evita que las partículas influyan en el hash y produzcan sustitutos sin sentido.',
      particlesToPreserveFile: 'Archivo con las partículas que deben mantenerse en el resultado incluso tras el enmascaramiento (una por línea). P. ej. "de", "del" — el sustituto generado conserva las partículas de la entrada original.',
      maxLengthOfMaskedName: 'Longitud máxima del nombre sustituto, en caracteres. Los nombres del archivo de lookup más largos se descartan en la selección. Útil cuando la columna de la base de datos tiene límite de tamaño.',
      maxNumberNames: 'Número máximo de nombres devueltos cuando el algoritmo opera en modo multivalor. Para un uso simple (un solo campo), déjalo vacío.',
      filterAccent: 'Si es verdadero, elimina los acentos de la entrada antes de calcular el hash de selección. Útil para tratar "Jose" y "José" como equivalentes, de modo que produzcan el mismo nombre enmascarado.',
      inputCaseSensitive: 'Si es verdadero, "Juan" y "JUAN" se tratan como entradas distintas y pueden producir sustitutos distintos. Si es falso (por defecto), la comparación ignora mayúsculas y minúsculas.',
    },
    labels: {
      lookupFile: 'Archivo de nombres sustitutos',
      maskedValueCase: 'Capitalización del resultado',
      particlesToRemoveFile: 'Archivo de partículas a eliminar (p. ej. "de", "del")',
      particlesToPreserveFile: 'Archivo de partículas a conservar en el resultado',
      maxLengthOfMaskedName: 'Longitud máxima del nombre sustituto',
      maxNumberNames: 'Número máximo de nombres (modo multivalor)',
      filterAccent: 'Ignorar acentos al elegir el sustituto',
      inputCaseSensitive: 'Distinguir mayúsculas y minúsculas en la entrada',
    },
  },
  FullName: {
    example: { input: 'Juan Carlos Pérez García', key: 'clave-nombre' },
    description: 'Enmascara un nombre completo separando el/los nombre(s) de pila del apellido y aplicando un algoritmo distinto a cada parte. La división se hace por espacios (o por los separadores configurados).',
    inputFormat: 'Nombre completo con espacios. P. ej. "Juan de la Cruz", "María Oliveira Santos".',
    params: {
      lastNameAtTheEnd: 'Indica dónde está el apellido. true = el apellido es la última palabra ("Juan Pérez" → apellido "Pérez"). false = el apellido es la primera palabra ("Pérez Juan" → apellido "Pérez").',
      ifSingleWordConsiderAsLastName: 'Qué hacer cuando la entrada tiene una sola palabra. true = tratarla como apellido y aplicar lastNameAlgorithmRef. false = tratarla como nombre de pila y aplicar firstNameAlgorithmRef.',
      firstNameAlgorithmRef: 'Algoritmo aplicado al/los nombre(s) de pila. Indica el nombre de una instancia del catálogo (p. ej. "dlpx-core:FirstName"). Si se omite, los nombres de pila se conservan sin enmascarar.',
      lastNameAlgorithmRef: 'Algoritmo aplicado al apellido. Indica el nombre de una instancia del catálogo (p. ej. "dlpx-core:LastName"). Si se omite, el apellido se conserva sin enmascarar.',
      lastNameSeparators: 'Cadenas que separan el apellido del/los nombre(s) de pila, además del espacio por defecto. P. ej. ["-"] para leer "María-Pérez" como nombre "María" y apellido "Pérez". Útil para nombres con guion u otros delimitadores.',
      maxLengthOfMaskedName: 'Longitud máxima del nombre completo enmascarado, en caracteres. Si el resultado la supera, el algoritmo trunca o rechaza. Útil cuando la columna tiene límite de tamaño.',
      maxNumberFirstNames: 'Número máximo de nombres de pila a enmascarar. Si la entrada tiene más, los sobrantes se conservan sin enmascarar. P. ej. "Juan Pedro Carlos Pérez" con maxNumberFirstNames=1 → solo se enmascara "Juan", se conserva "Pedro Carlos".',
    },
    labels: {
      lastNameAtTheEnd: 'El apellido va al final',
      ifSingleWordConsiderAsLastName: 'Palabra única = tratar como apellido',
      firstNameAlgorithmRef: 'Algoritmo para el/los nombre(s) de pila',
      lastNameAlgorithmRef: 'Algoritmo para el apellido',
      lastNameSeparators: 'Separadores adicionales de apellido',
      maxLengthOfMaskedName: 'Longitud máxima del nombre enmascarado',
      maxNumberFirstNames: 'Máximo de nombres de pila a enmascarar',
    },
  },
  FinancialIdBr: {
    example: { key: 'clave-cpf' },
    description: 'Enmascara los documentos brasileños CPF (11 dígitos) y CNPJ (14 dígitos) generando números sintéticos con dígitos de control válidos. Detecta el tipo automáticamente por la cantidad de dígitos.',
    inputFormat: 'CPF con o sin formato: "123.456.789-09" o "12345678909". CNPJ con o sin formato: "12.345.678/0001-90" o "12345678000190".',
    params: {
      maskInvalidInput: 'Qué hacer cuando el CPF/CNPJ de entrada es inválido (dígitos de control incorrectos o longitud errónea). false = lanza un error y se detiene (por defecto). true = lo enmascara igualmente, ignorando la invalidez.',
      cmNumericRef: 'Algoritmo de sustitución de dígitos usado internamente para barajar los números del CPF/CNPJ. Si no se configura, usa el Character Mapping numérico incorporado. Indica el nombre de una instancia del catálogo (p. ej. "dlpx-core:CM_Digits"). Déjalo vacío para usar el valor por defecto.',
      fallbackAlgorithm: 'Algoritmo aplicado cuando el valor de entrada no se reconoce ni como CPF ni como CNPJ (p. ej. el campo está en blanco o contiene texto fuera del formato). Si no se configura, el algoritmo lanza un error. Indica el nombre de una instancia del catálogo para tratar esos casos con elegancia.',
    },
    labels: {
      maskInvalidInput: 'Enmascarar aunque el CPF/CNPJ sea inválido',
      cmNumericRef: 'Algoritmo de sustitución de dígitos (Character Mapping)',
      fallbackAlgorithm: 'Algoritmo de reserva (formato no reconocido)',
    },
  },
  IBAN: {
    example: { key: 'clave-iban' },
    description: 'Enmascara un número IBAN conservando el código de país y los dígitos de control.',
    inputFormat: 'IBAN en el formato estándar. P. ej. "GB29NWBK60161331926819"',
    params: { validateInput: 'Obligatorio. Valida el IBAN antes de enmascarar.', numCharsToMask: 'Obligatorio. Número de caracteres a enmascarar.' },
    labels: { validateInput: 'Validar el IBAN antes de enmascarar', numCharsToMask: 'Cantidad de caracteres a enmascarar' },
  },
  Checkdigit: {
    example: { key: 'clave-check' },
    description: 'Enmascara los dígitos de un número que lleva dígito de control, recalculándolo después para que el resultado siga siendo válido. Funciona con cualquier esquema basado en suma ponderada más módulo (documentos, códigos de barras, EAN, etc.).',
    inputFormat: 'Cadena numérica sin puntuación ni espacios. Su longitud debe incluir el dígito de control en la posición configurada. P. ej. "12345678901", "7891000315507" (EAN-13), "123456789012".',
    params: {
      weightList: 'Obligatorio. Pesos aplicados a cada dígito en la suma ponderada. Un peso por dígito que participa en el cálculo (en orden de lectura o de derecha a izquierda, según calculateChecksumRightToLeft). P. ej. EAN-13 usa [1,3,1,3,1,3,1,3,1,3,1,3].',
      modulusNumber: 'Obligatorio. Divisor usado en el módulo de la suma ponderada. El dígito de control suele ser (módulo − resto) % módulo. P. ej. EAN-13 usa 10, CNPJ usa 11.',
      checkDigitIndex: 'Obligatorio. Posición del dígito de control en la cadena, contando desde el índice 0 (por la izquierda). P. ej. para un código de 13 dígitos cuyo control es el último, indica 12.',
      calculateChecksumRightToLeft: 'Obligatorio. Dirección en la que se aplican los pesos de weightList sobre los dígitos. true = de derecha a izquierda. false = de izquierda a derecha (convención EAN/UPC).',
      numDigitsForCheckdigitCalculation: 'Obligatorio. Cuántos dígitos participan en la suma ponderada (sin contar el propio dígito de control). Debe coincidir con la longitud de weightList. P. ej. EAN-13 tiene 12 dígitos de datos → indica 12.',
      swapModulusForZeroRemainder: 'Cuando el resto es cero, usa el propio modulusNumber como dígito de control en vez de cero. Algunos estándares adoptan esta regla. false = el dígito de control será 0 cuando el resto sea 0.',
      checksumCalculationType: 'Algoritmo de cálculo del checksum. STANDARD = suma ponderada simple módulo N (por defecto). TFN = la variante australiana (Tax File Number) con su propia lógica de cálculo.',
      numericAlgorithm: 'Algoritmo de enmascaramiento aplicado a los dígitos que no son el de control. Indica el nombre de una instancia del catálogo (p. ej. "dlpx-core:CM_Digits"). Si se omite, usa el Character Mapping numérico incorporado.',
      alphaNumericAlgorithm: 'Algoritmo de enmascaramiento usado cuando la entrada contiene letras además de números (alfanumérica). Se aplica a los caracteres no numéricos antes de recalcular el dígito de control. Si se omite y la entrada tiene letras, puede lanzar un error según characterHandling.',
      fallbackAlgorithm: 'Algoritmo aplicado cuando la entrada es inválida e invalidInputHandling = FALLBACK_MASK. Recibe el valor original completo. Si se omite y llega una entrada inválida con FALLBACK_MASK, el comportamiento queda indefinido.',
      preserveRegex: 'Expresión regular que identifica las partes de la cadena a dejar sin enmascarar (p. ej. prefijos fijos). Los fragmentos que coincidan se mantienen intactos; el algoritmo enmascara solo el resto.',
      'inputHandlingConfig': 'Ajustes sobre cómo tratar la entrada antes del enmascaramiento.',
      'inputHandlingConfig.characterHandling': 'Cómo tratar los caracteres no numéricos de la entrada. NUMERIC_ONLY = solo acepta 0-9 y rechaza el resto. STANDARD = las letras se tratan con su valor ASCII normal. ASCII_VALUE_MINUS_48 = usa (valorASCII − 48) para las letras, útil en algunos estándares que intercalan letras y dígitos.',
      'inputHandlingConfig.invalidInputHandling': 'Qué hacer cuando la entrada es inválida (longitud errónea, caracteres inesperados). ERROR = lanza una excepción (por defecto). FALLBACK_MASK = delega en fallbackAlgorithm en vez de fallar.',
      'inputHandlingConfig.shortInputHandling': 'Qué hacer cuando la entrada tiene menos dígitos de los esperados. FALLBACK = delega en fallbackAlgorithm. PAD_LEFT = rellena con padCharacter por la izquierda. PAD_RIGHT = rellena con padCharacter por la derecha.',
      'inputHandlingConfig.padCharacter': 'Carácter usado para rellenar entradas cortas cuando shortInputHandling = PAD_LEFT o PAD_RIGHT. Normalmente "0".',
      'inputHandlingConfig.trimWhitespace': 'Si es verdadero, elimina espacios y tabuladores de los extremos de la entrada antes de procesarla. Útil cuando los datos vienen con relleno de la base de datos.',
    },
    labels: {
      weightList: 'Lista de pesos (uno por dígito de datos)',
      modulusNumber: 'Módulo (divisor de la suma ponderada)',
      checkDigitIndex: 'Índice del dígito de control (base 0)',
      calculateChecksumRightToLeft: 'Aplicar los pesos de derecha a izquierda',
      numDigitsForCheckdigitCalculation: 'Dígitos en el cálculo (= longitud de weightList)',
      swapModulusForZeroRemainder: 'Usar el módulo cuando el resto sea cero',
      checksumCalculationType: 'Tipo de cálculo del checksum',
      numericAlgorithm: 'Algoritmo para dígitos numéricos',
      alphaNumericAlgorithm: 'Algoritmo para caracteres alfanuméricos',
      fallbackAlgorithm: 'Algoritmo de reserva (entrada inválida)',
      preserveRegex: 'Regex de las partes a conservar',
      inputHandlingConfig: 'Tratamiento de la entrada',
      'inputHandlingConfig.characterHandling': 'Tratamiento de caracteres no numéricos',
      'inputHandlingConfig.invalidInputHandling': 'Acción para entrada inválida',
      'inputHandlingConfig.shortInputHandling': 'Acción para entrada corta',
      'inputHandlingConfig.padCharacter': 'Carácter de relleno',
      'inputHandlingConfig.trimWhitespace': 'Quitar espacios de los extremos',
    },
  },
  Tokenization: {
    example: { key: 'clave-aes-fuerte' },
    description: 'Sustituye el valor por un token usando AES (Format-Preserving Encryption). El token tiene la misma longitud y los mismos tipos de carácter que el original (los dígitos siguen siendo dígitos, las letras siguen siendo letras). Es reversible: con la misma clave y configuración se puede recuperar el valor original — usa el botón "Destokenizar" para ello.',
    inputFormat: 'Cadena alfanumérica de formato fijo, como un número de tarjeta de crédito (16 dígitos) o un documento de identidad. Los caracteres fuera del conjunto tokenizable (símbolos, espacios) activan la reserva configurada.',
    params: {
      fallback: 'Qué hacer cuando el valor contiene caracteres que no se pueden tokenizar (p. ej. "@", "-", espacios). NONE lanza un error; CHARACTER_MAPPING sustituye esos caracteres por una máscara genérica y continúa.',
      ivLength: 'Tamaño del vector de inicialización AES en bytes (por defecto: 8). Los valores mayores añaden aleatoriedad al token, pero dejan menos espacio para los datos.',
      cmCharacterGroups: 'Solo relevante cuando fallback = CHARACTER_MAPPING. Define qué caracteres son intercambiables entre sí en la reserva — p. ej. ["0123456789", "abcdefghijklmnopqrstuvwxyz"] crea dos grupos separados. Si está vacío, usa los grupos por defecto del Character Mapping.',
      cmMinMaskedPositions: 'Solo relevante cuando fallback = CHARACTER_MAPPING. Número mínimo de posiciones que la reserva debe enmascarar, aunque haya pocos caracteres no tokenizables. Evita que un token con un solo carácter sustituido sea fácil de revertir.',
    },
    labels: {
      fallback: 'Acción de reserva para caracteres no tokenizables',
      ivLength: 'Tamaño del vector de inicialización (bytes)',
      cmCharacterGroups: 'Grupos de caracteres de la reserva (Character Mapping)',
      cmMinMaskedPositions: 'Posiciones mínimas enmascaradas por la reserva',
    },
  },
  MultiColumnAddress: {
    example: { input: 'Calle de las Flores, 123' },
    description: 'Enmascara campos de dirección repartidos en varias columnas generando direcciones sintéticas coherentes. ⚠️ Requiere un archivo de lookup de direcciones — no se puede probar en el runner standalone sin él. El algoritmo falla al inicializarse si el archivo no está configurado.',
    inputFormat: 'Cadena que representa un campo de dirección. Requiere un lookupFile configurado con una base de datos de direcciones en el formato específico de Delphix. No funciona con la configuración vacía.',
  },
  MultiColumnCondition: {
    example: { columns: [{ name: 'key', type: 'STRING', value: 'F' }, { name: 'string1', type: 'STRING', value: 'María' }] },
    description: 'Aplica algoritmos de enmascaramiento distintos a varias columnas según el valor de una columna condicional ("key"). P. ej. si GENERO="F", aplica FirstName a string1; si GENERO="M", aplica otro algoritmo. Cada condición define qué algoritmos usar para las columnas de tipo cadena, numérico, fecha y binario.',
    inputFormat: 'Fila de base de datos simulada con columnas con nombre. Columna obligatoria: "key" (el valor de la columna condicional). Columnas opcionales: "string1"…"string10", "numeric1"…"numeric3", "date1"…"date3".',
    params: {
      conditions: 'Array de condiciones. Cada una define: key (los valores que la activan) y los algoritmos a aplicar por ranura (string1..10, numeric1..3, date1..3, binary1..3). Por ejemplo key=["F"] + string1={name:"dlpx-core:FirstName"} enmascara la columna string1 con nombres femeninos cuando key="F".',
      'conditions.key': 'Valores de la columna condicional que activan esta condición. La comparación respeta keyCaseSensitive. P. ej. ["F", "Female"] se activa con "F" o "Female".',
      'conditions.string1': 'Algoritmo aplicado a la columna "string1" de la fila cuando esta condición se activa. Indica el nombre de una instancia del catálogo. P. ej. {name: "dlpx-core:FirstName"}.',
      'conditions.string2': 'Algoritmo aplicado a la columna "string2" cuando esta condición se activa.',
      'conditions.numeric1': 'Algoritmo aplicado a la columna "numeric1" (BigDecimal) cuando esta condición se activa.',
      'conditions.date1': 'Algoritmo aplicado a la columna "date1" (LocalDateTime) cuando esta condición se activa.',
      'conditions.binary1': 'Algoritmo aplicado a la columna "binary1" (ByteBuffer) cuando esta condición se activa.',
      fallbackAlgo: 'Algoritmo aplicado a las columnas de cadena cuando ninguna condición coincide con el valor de "key". Si no se configura, el valor se conserva sin enmascarar.',
      fallbackKey: 'Valor por defecto usado como clave cuando la columna "key" es nula o no está presente.',
      keyCaseSensitive: 'Si es verdadero, la comparación del valor de "key" con las listas de conditions.key distingue mayúsculas y minúsculas. Por defecto: false.',
      filterLength: 'Longitud máxima del valor de "key" usada en la comparación. Si el valor es más largo, solo se usan los primeros filterLength caracteres.',
      filterDirection: 'Desde qué extremo contar filterLength: LEFT (desde el inicio) o RIGHT (desde el final).',
    },
    labels: {
      conditions: 'Condiciones',
      'conditions.key': 'Valores de la columna condicional',
      'conditions.string1': 'Algoritmo para la columna string1',
      'conditions.string2': 'Algoritmo para la columna string2',
      'conditions.numeric1': 'Algoritmo para la columna numeric1',
      'conditions.date1': 'Algoritmo para la columna date1',
      'conditions.binary1': 'Algoritmo para la columna binary1',
      fallbackAlgo: 'Algoritmo de reserva (ninguna condición coincide)',
      fallbackKey: 'Clave por defecto cuando "key" es nulo',
      keyCaseSensitive: 'Comparación de clave sensible a mayúsculas',
      filterLength: 'Filtrar los primeros N caracteres de la clave',
      filterDirection: 'Dirección del filtro (LEFT / RIGHT)',
    },
  },
}
